SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../RTL/MAC/crc_core.sv
VERILOG_SOURCES += $(PWD)/tb.v
TOPLEVEL = tb
MODULE =  test
include $(shell cocotb-config --makefiles)/Makefile.SIM